// Generated by CoffeeScript 1.7.1

/*
	generator-joomla-component

	index.coffee

	@author Sean Goresht

	@note uses Codoc
	@see https://github.com/mklabs/yeoman/wiki/generators coffeescript with yeoman
	@see https://github.com/coffeedoc/codo
 */

(function() {
  "use strict";
  var ViewGenerator, path, yeoman,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  yeoman = require("yeoman-generator");

  path = require("path");


  /*
  	@class ControllerGenerator sub-generator for joomla component controllers
   */

  module.exports = ViewGenerator = (function(_super) {
    __extends(ViewGenerator, _super);

    function ViewGenerator(args, options, config) {
      var pkg, _ref, _ref1, _ref2, _ref3;
      ViewGenerator.__super__.constructor.call(this, args, options, config);
      pkg = JSON.parse(this.readFileAsString(path.join(process.cwd(), "./package.json")));
      this.componentName = pkg.componentName;
      this.description = pkg.description;
      this.requireManageRights = pkg.requireManageRights;
      this.authorName = (_ref = pkg.author) != null ? _ref.name : void 0;
      this.authorEmail = (_ref1 = pkg.author) != null ? _ref1.email : void 0;
      this.authorURL = (_ref2 = pkg.author) != null ? _ref2.url : void 0;
      this.license = (_ref3 = pkg.licenses[0]) != null ? _ref3.type : void 0;
      this.currentDate = new Date().getFullYear();
      this.viewFolderName = this._.slugify(this.name);
      this.viewClassName = this._.classify(this.name);
      console.log("You called the view subgenerator with the argument " + this.name + ".\nNow let's create that view under the subdirectory views/" + this.viewFolderName + "/view.html.php for you...");
    }

    ViewGenerator.prototype.generateController = function() {
      return this.template("_view.html.php", "views/" + this.viewFolderName + "/view.html.php");
    };

    return ViewGenerator;

  })(yeoman.generators.NamedBase);

}).call(this);

//# sourceMappingURL=index.map
